### ISSUE TITLE
Ruby | autoload script fails

### ISSUE THREAD

**Issue by gpolyn** [softasap/sa-ruby#1]
On OS X 10.10, `role_dir` does not work:
```
TASK [softasap.sa-ruby : Ruby | autoload script] *******************************
fatal: [web]: FAILED! => {"changed": false, "failed": true, "msg": "IOError: [Errno 2] No such file or directory: u'/Users/someusername/ansible/ansiblebook/ch06/roles/templates/ch_ruby.sh.j2'"}
```

**Comment by Voronenko** [comment]
Can you provide more details how do you execute provisioning? I am not sure that root cause is OSX 10.10 itself. Mentioned "/Users/someusername/ansible/ansiblebook/ch06/" is definitely completely wrong, but I am wondering what ansiblebook chapter 06 refers too ?  Perhaps your parent playbook overrides this variable role_dir causing play to fail.

**Comment by Voronenko** [comment]
Closing issue due to no response.
